# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pastila < Formula
  desc "Command line client for pastila.nl"
  homepage "https://github.com/jkaflik/pastila-cli"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkaflik/pastila-cli/releases/download/v0.0.3/pastila-cli_0.0.3_darwin_amd64.tar.gz"
      sha256 "71af3960ca4b4306c9dd57ac2a8935c0569180c7e53af344fc19ffaacd3d6f5b"

      def install
        bin.install "pastila"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkaflik/pastila-cli/releases/download/v0.0.3/pastila-cli_0.0.3_darwin_arm64.tar.gz"
      sha256 "a8368488f8d322ef47b6bdc042ef74c8397fb22011bbbf72a9762662e725c352"

      def install
        bin.install "pastila"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jkaflik/pastila-cli/releases/download/v0.0.3/pastila-cli_0.0.3_linux_amd64.tar.gz"
        sha256 "f8f9e80c3551385fcceb6ece245d2061c345181c3b2004ae7be4a96fdf25b334"

        def install
          bin.install "pastila"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jkaflik/pastila-cli/releases/download/v0.0.3/pastila-cli_0.0.3_linux_arm64.tar.gz"
        sha256 "e29c21d110f1505c50e4c28db1ebc2ba394c3538ecfa87fbb337720afa93ef2a"

        def install
          bin.install "pastila"
        end
      end
    end
  end

  test do
    system "#{bin}/pastila", "--help"
  end
end
