# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pastila < Formula
  desc "Command line client for pastila.nl"
  homepage "https://github.com/jkaflik/pastila-cli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jkaflik/pastila-cli/releases/download/v0.0.2/pastila-cli_0.0.2_darwin_amd64.tar.gz"
      sha256 "c76ae02db0ad8d49d591659df0a7745390741313a4a88690ee48281b99fc172a"

      def install
        bin.install "pastila"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jkaflik/pastila-cli/releases/download/v0.0.2/pastila-cli_0.0.2_darwin_arm64.tar.gz"
      sha256 "1d1255f366a7407b1cb800935c1e1b25e7dfd495fa74bde8ecc82bd85502bafb"

      def install
        bin.install "pastila"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jkaflik/pastila-cli/releases/download/v0.0.2/pastila-cli_0.0.2_linux_amd64.tar.gz"
        sha256 "e219d5d9112b3ee9f16c62d5fa886f120e55baa003167077562c3af613cf6d5f"

        def install
          bin.install "pastila"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jkaflik/pastila-cli/releases/download/v0.0.2/pastila-cli_0.0.2_linux_arm64.tar.gz"
        sha256 "f25ff7bd3d05daba81bc125b9b2e25123a5c15ed3b1740e405f28dba5614a318"

        def install
          bin.install "pastila"
        end
      end
    end
  end

  test do
    system "#{bin}/pastila", "--help"
  end
end
